add NUI Components guide
dalihub/dalihub.github.io pull request #4
Opened 2019-08-20 06:50 UTC by junqingma

add guide for Tizen.NUI.Components

2019-08-20 09:44 UTC, elishateng approved these changes
Look good to me.

2019-08-20 10:53 UTC, huayongxu approved these changes
It is great!

2019-08-21 07:08 UTC, liangliangzh approved these changes
it looks good to me

2019-08-21 22:42 UTC, agnelovaz requested changes
- I like that the guide is detailed but think each component should first show a simple example so not to scare the user.
- We should be generic in words and examples so not make NUI seem it has limited scope/possible customers.

- Chapters like the drop down look nice with the example images.

- Thinking if some screen shots of applications using the components would make it look even better?

- I resisted grammar comments at this time so not to distract from the main content review.

2019-08-21 22:42 UTC, agnelovaz commented on docs/nui-components/Guide.md
> +# Welcome to CommonUI
We are using the name NUI Components instead of CommonUI I believe.

2019-08-21 22:42 UTC, agnelovaz commented on docs/nui-components/Guide.md
> +Cover the common UI components of FHUB, TV, Mobile, Watch.
No need to mention targets as want NUI to seem general and useful for multiple applications.

2019-08-21 22:42 UTC, agnelovaz commented on docs/nui-components/Guide.md
> +Support R2L
RtL but shouldn't use abbreviations like that, "Support right to left languages"

2019-08-21 22:42 UTC, agnelovaz commented on docs/nui-components/Guide.md
> +CommonUI repositories are avaiable in GitHub with instructions to install and build.
link to the github repo or remove this instruction

2019-08-21 22:42 UTC, agnelovaz commented on docs/nui-components/Button.md
> +ButtonAttributes familyBasicButtonAttributes = new ButtonAttributes
Its nice to have a detailed example of a button with many levels of images and 2 styles but first we should start with a simple button example.  A single background image and some text.  Later in the guide we can have this full example.

2022-03-29 14:05 UTC, adeelkazmi approved these changes

2022-03-29 14:05 UTC, merged