Multiple Window User Guide
dalihub/dalihub.github.io pull request #5
Opened 2019-08-29 10:15 UTC by hrdisaac

2019-08-29 17:38 UTC, adeelkazmi approved these changes

2019-08-29 18:06 UTC, agnelovaz requested changes

2019-08-29 18:06 UTC, agnelovaz commented on docs/nui-tutorials/window.md
> +~~~
Add a link to the ResizeEvent chapter.

2019-08-29 18:06 UTC, agnelovaz commented on docs/nui-tutorials/window.md
> +The main window cannot be deleted, otherwise it will cause unexpected behaviour.
Update comment as not unexpected behavior (update TizenFX API comment too)

2019-08-29 18:06 UTC, agnelovaz commented on docs/nui-tutorials/window.md
> +Suppose there are two windows and each window has two buttons (as shown in the above diagram). We want to move focus between the buttons in these two windows using "Left" and "Right" navigation keys.
Move this to above the image and update (as shown in the ..... diagram)

2019-08-29 18:06 UTC, agnelovaz commented on docs/nui-tutorials/window.md
> +By default, the main window is created in full screen size, except that if running on the desktop the default size of the main window is set by the **set-env** script. The default main window size ca
"By default, the main window is created in full screen size, except that if running on the desktop the default size of the main window is set by the **set-env** script."

Thinking this is best mentioned after the  DALI_WINDOW_WIDTH=1920 DALI_WINDOW_HEIGHT=1080 my-app line as don't think most new users will know set-env well.

2019-08-30 10:46 UTC, agnelovaz approved these changes

2019-08-30 10:51 UTC, merged